Add suse tests to pipeline
candlepin/candlepin-jobs pull request #10
Opened 2017-02-15 19:11 UTC by kahowell

Feel free to review, but not appropriate to merge until the suse branches are all merged in subscription-manager.

2017-03-17 20:43 UTC, kahowell commented
104f28c..326cc32: rebase against master

2017-05-24 19:51 UTC, Lorquas commented
326cc32e830cd14c50c449bb978cecffeae6a810 ..  5347b1bf2f93a04472597c249ccfb4b9d90af96a : rebase against master

2017-05-24 19:57 UTC, Lorquas approved these changes
looks good to me as is.

Is there any way to add something like this to simplify code since we're calling it all over the place?

```groovy
def smartGithubNotify = {ref, status,  context,  targetUrl ->
  String desc = ""
  switch (status) {
    case 'PENDING':
      desc = PENDING_MESSAGE
      break
    case 'SUCCESS':
      desc = SUCCESS_MESSAGE
      break
    case 'FAILURE':
      desc = FAILURE_MESSAGE
      break
  }

  ref.with(
    githubNotify(
        account: GITHUB_ACCOUNT,
        repo: GITHUB_REPO,
        credentialsId: GITHUB_CREDENTIALS_ID,
        sha: GITHUB_COMMIT,
        status: status,
        description: desc,
        context: context,
        targetUrl: targetUrl))
 }
```
calling with:
```groovy
smartGithubNotify(
              this,
              status: 'PENDING',
              context: 'python-rhsm-python3',
              targetUrl: BUILD_URL)
```

or does that run into the crazy pipline closures problems like before?

2017-06-16 20:14 UTC, kahowell commented
Changes:
 - Refactor the subman pipeline into the patterns developed for the
candlepin pipeline.
 - Remove sles11 jobs, since right now sles11 builds are blocked by
python-six not being available, along with other various issues.
 - Make a few fix to the suse jobs for issues found in smoketesting.
 - s/Candlepin Performance/CandlepinPerformance

2017-06-16 20:41 UTC, cnsnyder requested changes

2017-06-16 20:41 UTC, cnsnyder commented on jobs/submanPipeline.groovy
> +    boolean enabled = Jenkins.instance.getItem(args.job, currentBuild.rawBuild.parent, Item.class).buildable
Perhaps surround this in a try catch. I've recently seen with the candlepin pipeline somewhat cryptic failure messages that arise due to changes to the job name (Changed one job from "Candlepin Performance" to "CandlepinPerformance").

Non-nacking, but please consider!

2017-06-19 18:32 UTC, kahowell commented
2dcd69d..15f606f: skip job if it can't be found

2017-06-19 18:32 UTC, kahowell commented on jobs/submanPipeline.groovy
> +    boolean enabled = Jenkins.instance.getItem(args.job, currentBuild.rawBuild.parent, Item.class).buildable
@cnsnyder done!

2017-06-20 14:52 UTC, cnsnyder approved these changes
LGTM!

2017-06-20 14:52 UTC, merged