vagrant works now, also added candlepin tab
candlepin/candlepin-jobs pull request #14
Opened 2017-05-01 17:54 UTC by Lorquas

vendoring uno-choice and scriptlr jenkins plugins.

2017-05-09 15:24 UTC, kahowell requested changes
I don't think we need the extracted plugins... It should be sufficient to just bundle the jpi or hpi... Also left a suggestion re `chown`. Otherwise looks good.

2017-05-09 15:24 UTC, kahowell commented on Vagrantfile
> +  config.vm.provision "shell", inline: $script
I would prefer this inlined:
```ruby
config.vm.provision "shell", inline: 'chown -R jenkins:jenkins /vagrant'
```

2017-05-11 20:46 UTC, Lorquas commented on Vagrantfile
> +  config.vm.provision "shell", inline: $script
woops, removed the extracted.  

and inlined it.

2017-05-16 14:08 UTC, kahowell approved these changes

2017-05-16 14:08 UTC, merged